language: php

sudo: false

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source

before_script:
  - bash vendor/frozzare/wp-test-suite/bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION
  - bash tests/bin/install-wp-cli.sh

script:
  - vendor/bin/phpunit --coverage-clover clover.xml
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/behat; fi

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - bash <(curl -s https://codecov.io/bash)

env:
  global:
    - WP_CLI_BIN_DIR=/tmp/wp-cli-phar
    - WP_CLI_CONFIG_PATH=/tmp/wp-cli-phar/config.yml

cache:
  directories:
  - $HOME/.composer/cache

matrix:
  include:
    - php: 5.5.9
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 5.5
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.6
      env: WP_VERSION=4.0 WP_MULTISITE=0
    - php: hhvm
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=0
    - php: 7.0
      env: WP_VERSION=nightly WP_MULTISITE=0
  allow_failures:
    - php: 7.0
      env: WP_VERSION=nightly WP_MULTISITE=0
  fast_finish: true

branches:
  only:
    - master
    - 2.x
    - 3.x
